language: node_js
node_js:
- 4
- 6
- 8
- 10
matrix:
  include:
  - node_js: 8
    env: TEST_SUITE=browser
cache:
  directories:
  - node_modules
sudo: false
install:
- npm -g install npm@5.10
- npm install
- npm prune
script: "./travis_tests.sh"
after_success:
- npm run coveralls
jobs:
  include:
  - stage: npm release
    script: echo "Publishing to npm..."
    node_js: 8
    if: tag =~ ^v\d+\.\d+\.\d+$
    deploy:
      provider: npm
      email: engineering+npm@particle.io
      api_key:
        secure: JzhJNTYb5bZmETc+MN7ivqeXTSUPMJ+ImGtiSXMFPNGnZc8PSwp82Q9Yx+cvno/8sSGaisleIcWDJ/4d9Vq6fNVchftu2tjCIauRUaQUf07tvO2bXW9HWmTaYCpySmvHsZD+v3FFOPEyWwkHWBGO0pQnlWOlPeJrzrpyp006uoh7shefK147zKwwUmZKJC0/VDbGOyWXeDXe1C0AapwxFovTaINir4OROmPCrmUX0ZzWQqWn6edyYZHMDDLLrAIywqiuj1f7MU5M4y+0lILVm0SC79x7fIm6ZnIk+V1KxbNYN1zrKAFLkGSRpVXbNPUULT/jxVFn+ThcSNidQf3cI5kX6sXfQLN8ue7MfMAYCcL3JZ4W0LkrsYn4RqC5t8D4VATTqsNMUn+oUDzgDm8NL8hW+RaE9hLkXEGz9NjMpXie4JThcJt/To6NEGDMd0hvzBcvKTG34xgsitM1XBnOe6uk/L4lx058hRshnIxHkctyvVQ/dZfHrRfTz6CkfC3UhSaw7ufKxBCceDId/DM2WDL2eUyy+ruJTbWhjbJv/GUBhR69atYriEqGmRmZSiA5nvj2+vTT6yrD0RbHi/CqhiEMFcZf3DI+mIrjXjmbvdKdt0cDUHazxxGSmU3S0EV+Qdvbv1pZxU/049WAnJWiwxwXHdpl9T6jZLw2e8d/xYs=
      skip_cleanup: true
      on:
        tags: true
